version: 2

jobs:
  build:
    working_directory: ~/comms-templates
    machine: true
    steps:
      - checkout

      - restore_cache:
         keys:
           - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
           - "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-master"

      - run: sbt test tut

      - save_cache:
          key: "{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}"
          paths:
            - ~/.sbt
            - target/resolution-cache
            - project/target/resolution-cache