addSbtPlugin("me.lessis"         % "bintray-sbt"         % "0.3.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"         % "1.0.3")
addSbtPlugin("org.tpolecat"      % "tut-plugin"          % "0.4.8")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"        % "0.6.4")
addSbtPlugin("org.lyranthe.sbt"  % "partial-unification" % "1.1.0")
addSbtPlugin("com.localytics"    % "sbt-dynamodb"        % "1.5.5")
