package com.ovoenergy.comms.templates.util

import com.ovoenergy.comms.model.{CommManifest, Marketing, Regulatory, Service}

trait PrdTemplates {

  val templates = Seq(
    CommManifest(Service, "props-green-electricity-bolton-confirmation-with-dd", "1.0"),
    CommManifest(Service, "props-green-bolton-cancellation", "5.0"),
    CommManifest(Service, "payg-credit-transfer-single", "2.0"),
    CommManifest(Marketing, "PAYGSmartMeterAvailabilityComm", "5.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_AMENDED_DUAL_ELECTRICITY", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_DUAL_GAS_FIRST", "2.0"),
    CommManifest(Service, "SmartMeterBookingConfirmation", "4.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_KNOWN_ELECTRICITY", "2.0"),
    CommManifest(Service, "orion-email-changed-new", "1.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_AMENDED_DUAL_DIFFERENT", "2.0"),
    CommManifest(Service, "boost-sms-test", "1.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_DUAL_GAS_LAST", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_DUAL_GAS_FIRST", "4.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_AMENDED_DUAL", "3.0"),
    CommManifest(Service, "cc-payment-taken", "0.3"),
    CommManifest(Service, "props-green-electricity-bolton-cancellation", "2.0"),
    CommManifest(Service, "canary", "21.0"),
    CommManifest(Service, "SmartMeterBookingCancellationBoost", "7.0"),
    CommManifest(Service, "apollo-password-reset", "1.0"),
    CommManifest(Service, "props-foundation-addon-confirmation-with-dd", "1.0"),
    CommManifest(Service, "canary-non-customer", "2.0"),
    CommManifest(Service, "SmartMeterBookingConfirmationLumo", "2.0"),
    CommManifest(Service, "SmartMeterBookingCancellation", "7.0"),
    CommManifest(Marketing, "get-voucher", "2.0"),
    CommManifest(Marketing, "PAYGSmartMeterAvailability2Comm", "1.0"),
    CommManifest(Service, "orion-email-changed-old", "1.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_DUAL_ELECTRICITY_LAST", "6.0"),
    CommManifest(Service, "polar-integration-sign-up-success-new-customer", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_DUAL", "2.0"),
    CommManifest(Service, "orion-password-changed", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SIGN_UP_CONFIRMATION_SET_UP_PASSWORD", "3.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SIGN_UP_CONFIRMATION_BROKER", "5.0"),
    CommManifest(Marketing, "PAYMSmartMeterAvailabilitySMS", "1.0"),
    CommManifest(Service, "corgi-homeheat-order-confirmation", "9.0"),
    CommManifest(Regulatory, "orion-annual-comm", "1.0"),
    CommManifest(Marketing, "PAYMSmartMeterBookingSMS", "1.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_ELECTRICITY", "3.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_DUAL", "4.0"),
    CommManifest(Service, "orion-password-reset", "8.0"),
    CommManifest(Service, "SimplySmartBooking", "1.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_KNOWN_DUAL", "3.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_AMENDED_ELECTRICITY", "2.0"),
    CommManifest(Service, "you-have-left-ovo", "13.0"),
    CommManifest(Service, "interest-reward-second-year", "1.0"),
    CommManifest(Service, "props-green-gas-bolton-confirmation-with-dd", "5.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_DUAL_ELECTRICITY_LAST", "3.0"),
    CommManifest(Regulatory, "Orion statement", "8.0"),
    CommManifest(Service, "polar-integration-sign-up-failed", "3.0"),
    CommManifest(Service, "props-green-electricity-bolton-confirmation-without-dd", "2.0"),
    CommManifest(Marketing, "PAYMSmartMeterAvailabilityComm", "3.0"),
    CommManifest(Service, "SmartMeterBookingCancellationBoost.zip", "1.0"),
    CommManifest(Service, "SmartMeterBookingCancellationLumo", "2.0"),
    CommManifest(Service, "props-foundation-addon-cancellation", "1.0"),
    CommManifest(Service, "props-green-bolton-confirmation-with-dd", "5.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_DUAL_ELECTRICITY_FIRST", "3.0"),
    CommManifest(Marketing, "get-link", "2.0"),
    CommManifest(Marketing, "LumoSmartMeterAvailability2Comm", "2.0"),
    CommManifest(Marketing, "LumoSmartMeterAvailabilityComm", "3.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_DUAL_ELECTRICITY_FIRST", "4.0"),
    CommManifest(Service, "SmartMeterBookingConfirmationBoost", "4.0"),
    CommManifest(Service, "polar-integration-sign-up-success", "3.0"),
    CommManifest(Service, "props-green-bolton-confirmation-without-dd", "4.0"),
    CommManifest(Service, "sprint-review-demo", "4.0"),
    CommManifest(Service, "payg-credit-transfer-dual", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SSD_AMENDED_DUAL_GAS", "3.0"),
    CommManifest(Service, "props-foundation-addon-confirmation-without-dd", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SIGN_UP_CONFIRMATION", "2.0"),
    CommManifest(Service, "interest-reward-third-year", "1.0"),
    CommManifest(Service, "props-green-gas-bolton-confirmation-without-dd", "5.0"),
    CommManifest(Service, "PAYG_ONBOARDING_SUPPLY_START_ELECTRICITY", "2.0"),
    CommManifest(Service, "PAYG_ONBOARDING_UPCOMING_SUPPLY_START_DUAL_GAS_LAST", "3.0"),
    CommManifest(Service, "ONBOARDING_SIGN_UP_CONFIRMATION_BROKER", "1.0"),
    CommManifest(Service, "props-green-electricity-bolton-confirmation", "1.0"),
    CommManifest(Service, "interest-reward-first-year", "1.0"),
    CommManifest(Service, "props-green-gas-bolton-cancellation", "4.0"),
    CommManifest(Marketing, "PAYMSmartMeterAvailability2Comm", "2.0")
  )
}