package com.ovoenergy.comms.templates.util

import com.ovoenergy.comms.model.{CommManifest, Service}

trait UatTemplates {

  val uat = Seq(
    CommManifest(Service, "Ovo Sample Test Large Image", "1"),
    CommManifest(Service, "Ovo Sample Test Large Image", "2"),
    CommManifest(Service, "test3", "1.0"),
    CommManifest(Service, "payg-credit-transfer-single", "0.1"),
    CommManifest(Service, "PrintSample", "1.0"),
    CommManifest(Service, "PrintSample", "2.0"),
    CommManifest(Service, "PrintSample", "3.0"),
    CommManifest(Service, "PrintSample", "4.0"),
    CommManifest(Service, "PrintSample", "5.0"),
    CommManifest(Service, "PrintSample", "6.0"),
    CommManifest(Service, "PrintSample", "7.0"),
    CommManifest(Service, "PrintSample", "8.0"),
    CommManifest(Service, "PrintSample", "9.0"),
    CommManifest(Service, "PrintSample", "10.0"),
    CommManifest(Service, "PrintSample", "11.0"),
    CommManifest(Service, "PrintSample", "12.0"),
    CommManifest(Service, "PrintSample", "13.0"),
    CommManifest(Service, "PrintSample", "14.0"),
    CommManifest(Service, "PrintSample", "15.0"),
    CommManifest(Service, "PrintSample", "16.0"),
    CommManifest(Service, "PrintSample", "17.0"),
    CommManifest(Service, "PrintSample", "18.0"),
    CommManifest(Service, "PrintSample", "19.0"),
    CommManifest(Service, "PrintSample", "20.0"),
    CommManifest(Service, "PrintSample", "21.0"),
    CommManifest(Service, "PrintSample", "22.0"),
    CommManifest(Service, "PrintSample", "23.0"),
    CommManifest(Service, "PrintSample", "24.0"),
    CommManifest(Service, "PrintSample", "25.0"),
    CommManifest(Service, "PrintSample", "26.0"),
    CommManifest(Service, "BoostSample", "1.0"),
    CommManifest(Service, "cc-payment-taken", "0.3"),
    CommManifest(Service, "version-test", "1.0"),
    CommManifest(Service, "version-test", "2.0"),
    CommManifest(Service, "version-test", "3.0"),
    CommManifest(Service, "email-and-sms", "1.0"),
    CommManifest(Service, "example-for-docs", "1.0"),
    CommManifest(Service, "canary", "0.1"),
    CommManifest(Service, "canary", "0.2"),
    CommManifest(Service, "canary", "1.0"),
    CommManifest(Service, "canary", "2.0"),
    CommManifest(Service, "canary", "3.0"),
    CommManifest(Service, "canary", "4.0"),
    CommManifest(Service, "TestTemplate", "1.0"),
    CommManifest(Service, "yolo", "1.0"),
    CommManifest(Service, "gfd", "1.0"),
    CommManifest(Service, "gfd", "2.0"),
    CommManifest(Service, "gfd", "3.0"),
    CommManifest(Service, "gfd", "4.0"),
    CommManifest(Service, "gfd", "5.0"),
    CommManifest(Service, "gfd", "6.0"),
    CommManifest(Service, "gfd", "7.0"),
    CommManifest(Service, "gfd", "8.0"),
    CommManifest(Service, "sfsdfs", "1"),
    CommManifest(Service, "test4", "1.0"),
    CommManifest(Service, "test4", "2.0"),
    CommManifest(Service, "test5", "1.0"),
    CommManifest(Service, "test5", "2.0"),
    CommManifest(Service, "test5", "3.0"),
    CommManifest(Service, "test5", "4.0"),
    CommManifest(Service, "test5", "5.0"),
    CommManifest(Service, "test5", "6.0"),
    CommManifest(Service, "test5", "7.0"),
    CommManifest(Service, "testy-mc-testface", "1.0"),
    CommManifest(Service, "Test4", "1"),
    CommManifest(Service, "steve-test", "1.0"),
    CommManifest(Service, "steve-test", "2.0"),
    CommManifest(Service, "steve-test", "3.0"),
    CommManifest(Service, "steve-test", "4.0"),
    CommManifest(Service, "dffdgdgd", "1.0"),
    CommManifest(Service, "Test5", "1.0"),
    CommManifest(Service, "print-sample", "1.0"),
    CommManifest(Service, "payg-credit-transfer-dual", "0.1"),
    CommManifest(Service, "Test1", "1.0"),
    CommManifest(Service, "Ovo Sample Test", "1.0"),
    CommManifest(Service, "Ovo Sample Test", "2.0"),
    CommManifest(Service, "Ovo Sample Test", "3.0"),
    CommManifest(Service, "Ovo Sample Test", "4.0"),
    CommManifest(Service, "test1", "1.0")
  )

}
